**LATIHAN PERTEMUAN PERTAMA**
**SUSTRI ELINA SIMAMORA**
**NIM: 3012310040**

In [32]:
import numpy as np
import pandas as pd

In [2]:
#Matriks 1 Dimensi
Matrik1D=np.array([2,3,4,5])
print("Array 1 Dimensi: ", Matrik1D)

Array 1 Dimensi:  [2 3 4 5]


In [3]:
#Matriks 2 Dimensi
Matrik2D=np.array([[2,3,4,5],[6,7,8,9]])
print("Array 2 Dimensi: ", Matrik2D)

Array 2 Dimensi:  [[2 3 4 5]
 [6 7 8 9]]


In [4]:
#mMatriks 3 Dimensi
Matrik3D=np.array([[[2,3,4],[6,7,8]],[[0,1,2],[3,4,5]]])
print("Array 3 Dimensi: ", Matrik3D)

Array 3 Dimensi:  [[[2 3 4]
  [6 7 8]]

 [[0 1 2]
  [3 4 5]]]


JENIS-JENIS **ARRAY**

In [5]:
#1.Array of ones
ones=np.ones((2,3,4,5))
print("Array satuan", ones)

Array satuan [[[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1.]]]]


In [6]:
#2.Array of zeros
zeros=np.zeros((2,3,4,5,))
print("Array nol",zeros)

Array nol [[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]


In [7]:
#3.Array with random values
random=np.random.random((2,3,4,5))
print("Array Random", random)

Array Random [[[[0.73061243 0.41911349 0.27077127 0.872634   0.60103698]
   [0.62689681 0.68957332 0.67791566 0.27138344 0.91333551]
   [0.67849238 0.95946591 0.90050833 0.5717612  0.20972051]
   [0.8452894  0.75806341 0.63836838 0.26707527 0.01726612]]

  [[0.87421718 0.61725563 0.95427833 0.57264741 0.10222001]
   [0.991266   0.45834796 0.75943511 0.71510476 0.72819685]
   [0.87118425 0.88283216 0.40612079 0.06389308 0.31078595]
   [0.17653064 0.62160863 0.45904864 0.68669552 0.65106339]]

  [[0.91879042 0.39297063 0.4597809  0.48374537 0.65713362]
   [0.37361091 0.3823995  0.26055257 0.71157684 0.08321538]
   [0.4857879  0.4487104  0.19583549 0.16517536 0.33739275]
   [0.27186716 0.53857582 0.39232563 0.48846419 0.03611385]]]


 [[[0.07780758 0.73144867 0.3075887  0.29587939 0.42615169]
   [0.62497842 0.72648071 0.85652698 0.17170272 0.73732494]
   [0.06928576 0.02684266 0.0427075  0.65152026 0.18118087]
   [0.51467249 0.05150146 0.67967182 0.86571761 0.90671327]]

  [[0.22077902 0.

In [11]:
#4.Empty Array
empty=np.empty((2,2))
print("Array Kosong=", empty)

Array Kosong= [[5.14419984e-316 0.00000000e+000]
 [6.66381814e-310 6.66381814e-310]]


In [10]:
#5. Full Array
full=np.full((3,3),10)
print("Full array=", full)

Full array= [[10 10 10]
 [10 10 10]
 [10 10 10]]


Memberikan space pada array dengan perbadingan setiap baris 5

In [9]:
#6.Array Spaced Values
Array6=np.arange(10, 25,5)
print("Array=", Array6)

Array= [10 15 20]


In [8]:
#7.Linspace
Linspace=np.linspace(0,2,9)
print("Linspace=", Linspace)

Linspace= [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


**BASIC OPERATION**

In [12]:
x=np.array([[1,2,3,4],[1,0,1,0]])
y=np.array([[1,1,2,2],[3,3,4,4,]])

In [13]:
#Penjumlahan
Jumlah=np.add(x,y)
print("Hasil Penjumlahan=", Jumlah)

Hasil Penjumlahan= [[2 3 5 6]
 [4 3 5 4]]


In [14]:
#Pengurangan
Kurang=np.subtract(x,y)
print("Hasil Pengurangan", Kurang)

Hasil Pengurangan [[ 0  1  1  2]
 [-2 -3 -3 -4]]


In [18]:
z=np.full((3,3),2)
t=np.full((3,3),10)

In [19]:
#Perkalian
Kali=np.multiply(z,t)
print("Hasil Perkalian", Kali)

Hasil Perkalian [[20 20 20]
 [20 20 20]
 [20 20 20]]


In [23]:
#Pembagian
Bagi=np.divide(t,z)
print("Hasil pembagian", Bagi)

Hasil pembagian [[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]


In [24]:
#Modulus
Remainder=np.remainder(t,z)
print("Hasil Modulus", Remainder)

Hasil Modulus [[0 0 0]
 [0 0 0]
 [0 0 0]]


**INDEX**

In [29]:
#Menampilkan baris pada index 0 dan 1
print(x[0:2])
print(x[0:2])
#Menampilkan kolom ke 2
print(x[0:2,2])
print(x[:,2])
print(x[0])

[[1 2 3 4]
 [1 0 1 0]]
[[1 2 3 4]
 [1 0 1 0]]
[3 1]
[3 1]
[1 2 3 4]


In [30]:
#Nilai yang lebih besar dari 3
LebihBesar=(x>3)
print("Elemen lebih besar dari 3=",LebihBesar)
print(x[LebihBesar])

Elemen lebih besar dari 3= [[False False False  True]
 [False False False False]]
[4]


**DATAFRAME**

In [35]:
#1. Data frame series
series=pd.Series([2,3,4,5,6,7,8])
print(series)

0    2
1    3
2    4
3    5
4    6
5    7
6    8
dtype: int64


In [36]:
#2. Data frame dalam bentuk tabel
series_df=pd.DataFrame({
    'A': range(1,5),
    'B': pd.Timestamp('20240304'),
    'C': pd.Series(5, index=list(range(4)), dtype='float64'),
    'D': np.array([3]*4, dtype='int64'),
    'E': pd.Categorical(['Defresi','Anxiety','Biopolar','Eating Disorder']),
    'F': 'Mental Health',
    'G': 'is challenging'
})

print("Tabel MentaL Health")
print(series_df)

Tabel MentaL Health
   A          B    C  D                E              F               G
0  1 2024-03-04  5.0  3          Defresi  Mental Health  is challenging
1  2 2024-03-04  5.0  3          Anxiety  Mental Health  is challenging
2  3 2024-03-04  5.0  3         Biopolar  Mental Health  is challenging
3  4 2024-03-04  5.0  3  Eating Disorder  Mental Health  is challenging


In [37]:
#Creating DataFrame from Dictionary
dict_df=[{'A':'Apple', 'B':'Ball',}, {'A': 'Aeroplane', 'B': 'Bat', 'C': 'Cat'}]
print(pd.DataFrame(dict_df))

           A     B    C
0      Apple  Ball  NaN
1  Aeroplane   Bat  Cat


In [40]:
#Creating DataFrame from ndarrays (Array dengan ukuran N)
sdf={
    'Kota': ['Bandung', 'Bojonegoro', 'Malang', 'Gresik', 'Manado', 'TulungAgung'],
    'ISO-code': [1,2,3,4,5,6],
    'Area': [11,22,33,44,55,66],
    'Administration Centre':['A','B', 'C', 'D', 'E', 'F']
}
print(pd.DataFrame(sdf))

          Kota  ISO-code  Area Administration Centre
0      Bandung         1    11                     A
1   Bojonegoro         2    22                     B
2       Malang         3    33                     C
3       Gresik         4    44                     D
4       Manado         5    55                     E
5  TulungAgung         6    66                     F


**IMPORT DATA FROM CSV**

In [45]:
columns=['Umur','Kelas', 'fnlwgt', 'Pendidikan', 'Semester', 'Pernikahan',
        'Occupation', 'Relationship', 'Etnis', 'Jenis Kelamin', 'Capital_Gain',
        'Capital_Lose', 'Hours per Week', 'Negara Asal', 'Pendapatan']
df=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data',names=columns)
df.head()


Umur              Kelas  fnlwgt  Pendidikan  Semester           Pernikahan  \
0    39          State-gov   77516   Bachelors        13        Never-married   
1    50   Self-emp-not-inc   83311   Bachelors        13   Married-civ-spouse   
2    38            Private  215646     HS-grad         9             Divorced   
3    53            Private  234721        11th         7   Married-civ-spouse   
4    28            Private  338409   Bachelors        13   Married-civ-spouse   

           Occupation    Relationship   Etnis Jenis Kelamin  Capital_Gain  \
0        Adm-clerical   Not-in-family   White          Male          2174   
1     Exec-managerial         Husband   White          Male             0   
2   Handlers-cleaners   Not-in-family   White          Male             0   
3   Handlers-cleaners         Husband   Black          Male             0   
4      Prof-specialty            Wife   Black        Female             0   

   Capital_Lose  Hours per Week     Negara Asal Pendapatan  
0             0              40   United-States      <=50K  
1             0              13   United-States      <=50K  
2             0              40   United-States      <=50K  
3             0              40   United-States      <=50K  
4             0              40            Cuba      <=50K

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Umur            32561 non-null  int64 
 1   Kelas           32561 non-null  object
 2   fnlwgt          32561 non-null  int64 
 3   Pendidikan      32561 non-null  object
 4   Semester        32561 non-null  int64 
 5   Pernikahan      32561 non-null  object
 6   Occupation      32561 non-null  object
 7   Relationship    32561 non-null  object
 8   Etnis           32561 non-null  object
 9   Jenis Kelamin   32561 non-null  object
 10  Capital_Gain    32561 non-null  int64 
 11  Capital_Lose    32561 non-null  int64 
 12  Hours per Week  32561 non-null  int64 
 13  Negara Asal     32561 non-null  object
 14  Pendapatan      32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


**Menampilkan Data pada baris ke-n**

In [ ]:
df.iloc[5]

In [ ]:
df.iloc[1:20]

In [ ]:
df.iloc[10:15]

In [ ]:
#5 Baris Terakhir
df.iloc[-5]

In [ ]:
df.iloc[:2,5]

**Menampilkan Kolom**

In [56]:
#Kolom 3
df.iloc[:,3]

0          Bachelors
1          Bachelors
2            HS-grad
3               11th
4          Bachelors
            ...     
32556     Assoc-acdm
32557        HS-grad
32558        HS-grad
32559        HS-grad
32560        HS-grad
Name: Pendidikan, Length: 32561, dtype: object

In [58]:
#baris 2-5, kolom 3-5
df.iloc[2:5, 3:5]

Pendidikan  Semester
2     HS-grad         9
3        11th         7
4   Bachelors        13